---
title: "Pro"
author: "Prothila"
date: "11/30/2022"
output: html_document
---



```{r setup, include=FALSE}
plastics <- readr::read_csv('https://raw.githubusercontent.com/rfordatascience/tidytuesday/master/data/2021/2021-01-26/plastics.csv')
```




```{r} 
library(tidyverse)

plastics_new <- plastics %>%
  select("country","empty", "hdpe", "ldpe", "o", "pet", "pp", "ps", "pvc",
         "grand_total")

plastics_version <-
  plastics_new %>%
  group_by(country) %>%
  summarize(EMPTY = sum(empty),
            HDPE = sum(hdpe),
            LDPE = sum(ldpe),
            OTHERS = sum(o),
            PET = sum(pet),
            PP = sum(pp),
            PS = sum(ps),
            PVC = sum(pvc),
            grand_total = sum(grand_total),
            total = sum(EMPTY, HDPE, LDPE, OTHERS, PET, PP, PS, PVC, na.rm = TRUE)) %>%
  filter(country != c("NIGERIA")) %>%
  filter(country != c("ECUADOR")) %>%
  filter(country != c("EMPTY"))  %>% 
  select("country","HDPE","LDPE","PET","OTHERS","PP","PS","PVC","total") %>% 
  rename ('High density polyethylene' = HDPE,
         'Low density polyethylene' = LDPE,
         'Polyester plastic' = PET,
         'Polypropylene' = PP,
         'Polystyrene' = PS,
         'Polyvinyl Chloride' = PVC,
         'Other plastic'= OTHERS,
         'Total'= total)

library('DT')
datatable(plastics_version)
```



