---
title: "Pro"
author: "Prothila"
date: "11/30/2022"
output: html_document
---

```{r setup, include=FALSE}
plastics <- readr::read_csv('https://raw.githubusercontent.com/rfordatascience/tidytuesday/master/data/2021/2021-01-26/plastics.csv')


plastics_new <- plastics %>% 
  select("country", "hdpe", "ldpe", "o", "pet", "pp", "ps", "pvc",
         "grand_total")

plastics_version <- 
  plastics_new %>%
  group_by(country) %>%
  summarize(hdpe = sum(hdpe),
            ldpe = sum(ldpe),
            others = sum(o),
            pet = sum(pet),
            pp = sum(pp),
            ps = sum(ps),
            grand_total = sum(grand_total)) %>% 
  filter(country != "NIGERIA")

head (plastics_version)
```



```{r}
library(dplyr)
plastics_version <- plastics_version %>% 
  rename ('high_density_polyethylene' = hdpe,
         'low_density_polyethylene' = ldpe,
         'polyester_plastic' = pet,
         'polypropylene' = pp,
         'polystyrene' = ps,
         'other_plastic'= others,
         'total'= grand_total)

library('DT')
library('plotly')
datatable(plastics_version)

datatable (plastics_version, colnames = c("Country", "High density polyethylene", "low_density_polyethylene", "other_plastic", "Polyester_plastic", "Polypropylene", "Polystyrene", "pvc",
         "grand_total"),
         extensions = "Scroller", style="bootstrap", class="compact", width="100%", options=list(deferRender=TRUE, scrollY=300, scroller=TRUE))
  
```


